"""make_challenge_columns_nullable

Revision ID: 6b56a3ef6fe0
Revises: 958a44081315
Create Date: 2026-07-04 12:44:43.573571

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "6b56a3ef6fe0"
down_revision: Union[str, Sequence[str], None] = "958a44081315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_challenges", schema=None) as batch_op:
        batch_op.alter_column("prompt", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("image_url", existing_type=sa.VARCHAR(length=512), nullable=True)
        batch_op.alter_column("target_embedding", existing_type=sqlite.JSON(), nullable=True)
        batch_op.alter_column(
            "embedding_model_name", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prompt_challenges", schema=None) as batch_op:
        batch_op.alter_column(
            "embedding_model_name", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column("target_embedding", existing_type=sqlite.JSON(), nullable=False)
        batch_op.alter_column("image_url", existing_type=sa.VARCHAR(length=512), nullable=False)
        batch_op.alter_column("prompt", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
