"""Initial MVP schema

Revision ID: 7d02c363f9df
Revises:
Create Date: 2026-07-04 01:36:52.041899

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.models.challenge

# revision identifiers, used by Alembic.
revision: str = "7d02c363f9df"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'abandoned')", name="valid_session_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_sessions_id"), "game_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_game_sessions_status"), "game_sessions", ["status"], unique=False)
    op.create_table(
        "prompt_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("target_embedding", app.models.challenge.SafeVector(dim=768), nullable=False),
        sa.Column("embedding_model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_challenges_category"), "prompt_challenges", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_challenges_difficulty"), "prompt_challenges", ["difficulty"], unique=False
    )
    op.create_index(op.f("ix_prompt_challenges_id"), "prompt_challenges", ["id"], unique=False)
    op.create_table(
        "game_rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_session_id", sa.Integer(), nullable=False),
        sa.Column("prompt_challenge_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("guess_text", sa.String(length=512), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_session_id"], ["game_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prompt_challenge_id"], ["prompt_challenges.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_session_id", "prompt_challenge_id", name="uq_game_round_session_challenge"
        ),
    )
    op.create_index(op.f("ix_game_rounds_id"), "game_rounds", ["id"], unique=False)
    op.create_index(
        op.f("ix_game_rounds_is_completed"), "game_rounds", ["is_completed"], unique=False
    )
    op.create_index(
        op.f("ix_game_rounds_prompt_challenge_id"),
        "game_rounds",
        ["prompt_challenge_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_rounds_prompt_challenge_id"), table_name="game_rounds")
    op.drop_index(op.f("ix_game_rounds_is_completed"), table_name="game_rounds")
    op.drop_index(op.f("ix_game_rounds_id"), table_name="game_rounds")
    op.drop_table("game_rounds")
    op.drop_index(op.f("ix_prompt_challenges_id"), table_name="prompt_challenges")
    op.drop_index(op.f("ix_prompt_challenges_difficulty"), table_name="prompt_challenges")
    op.drop_index(op.f("ix_prompt_challenges_category"), table_name="prompt_challenges")
    op.drop_table("prompt_challenges")
    op.drop_index(op.f("ix_game_sessions_status"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_id"), table_name="game_sessions")
    op.drop_table("game_sessions")
    # ### end Alembic commands ###
