"""gameplay_5_attempts

Revision ID: 958a44081315
Revises: e07012490619
Create Date: 2026-07-04 02:41:50.623856

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "958a44081315"
down_revision: Union[str, Sequence[str], None] = "e07012490619"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guess_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_session_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("guess_text", sa.String(length=1000), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("evaluation_feedback", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_number BETWEEN 1 AND 5", name=op.f("ck_guess_attempts_valid_attempt_number")
        ),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
            name=op.f("fk_guess_attempts_game_session_id_game_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guess_attempts")),
        sa.UniqueConstraint(
            "game_session_id", "attempt_number", name="uq_guess_attempt_session_number"
        ),
    )
    with op.batch_alter_table("guess_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guess_attempts_game_session_id"), ["game_session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_guess_attempts_id"), ["id"], unique=False)

    with op.batch_alter_table("game_rounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_rounds_id"))
        batch_op.drop_index(batch_op.f("ix_game_rounds_is_completed"))
        batch_op.drop_index(batch_op.f("ix_game_rounds_prompt_challenge_id"))

    op.drop_table("game_rounds")
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt_challenge_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("attempts_used", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("best_score", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_game_sessions_prompt_challenge_id"),
            ["prompt_challenge_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_game_sessions_prompt_challenge_id_prompt_challenges"),
            "prompt_challenges",
            ["prompt_challenge_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("score")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("score", sa.INTEGER(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_game_sessions_prompt_challenge_id_prompt_challenges"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_game_sessions_prompt_challenge_id"))
        batch_op.drop_column("completed_at")
        batch_op.drop_column("best_score")
        batch_op.drop_column("attempts_used")
        batch_op.drop_column("prompt_challenge_id")

    op.create_table(
        "game_rounds",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("game_session_id", sa.INTEGER(), nullable=False),
        sa.Column("prompt_challenge_id", sa.INTEGER(), nullable=False),
        sa.Column("score", sa.INTEGER(), nullable=False),
        sa.Column("is_completed", sa.BOOLEAN(), nullable=False),
        sa.Column("guess_text", sa.VARCHAR(length=512), nullable=True),
        sa.Column("similarity_score", sa.FLOAT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game_sessions.id"],
            name=op.f("fk_game_rounds_game_session_id_game_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_challenge_id"],
            ["prompt_challenges.id"],
            name=op.f("fk_game_rounds_prompt_challenge_id_prompt_challenges"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_rounds")),
        sa.UniqueConstraint(
            "game_session_id", "prompt_challenge_id", name=op.f("uq_game_round_session_challenge")
        ),
    )
    with op.batch_alter_table("game_rounds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_game_rounds_prompt_challenge_id"), ["prompt_challenge_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_rounds_is_completed"), ["is_completed"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_game_rounds_id"), ["id"], unique=False)

    with op.batch_alter_table("guess_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guess_attempts_id"))
        batch_op.drop_index(batch_op.f("ix_guess_attempts_game_session_id"))

    op.drop_table("guess_attempts")
    # ### end Alembic commands ###
