"""add_player_id_to_game_sessions

Revision ID: b8556481fe05
Revises: 6b56a3ef6fe0
Create Date: 2026-07-04 13:39:05.173671

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8556481fe05"
down_revision: Union[str, Sequence[str], None] = "6b56a3ef6fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("player_id", sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f("ix_game_sessions_player_id"), ["player_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_game_session_player_challenge", ["player_id", "prompt_challenge_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_game_session_player_challenge", type_="unique")
        batch_op.drop_index(batch_op.f("ix_game_sessions_player_id"))
        batch_op.drop_column("player_id")

    # ### end Alembic commands ###
