"""daily_challenge_schema

Revision ID: e07012490619
Revises: 7d02c363f9df
Create Date: 2026-07-04 02:12:19.465536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e07012490619"
down_revision: Union[str, Sequence[str], None] = "7d02c363f9df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt_challenges", sa.Column("status", sa.String(length=20), nullable=False))
    op.add_column("prompt_challenges", sa.Column("publish_date", sa.Date(), nullable=True))
    op.drop_index(op.f("ix_prompt_challenges_category"), table_name="prompt_challenges")
    op.drop_index(op.f("ix_prompt_challenges_difficulty"), table_name="prompt_challenges")
    op.create_index(
        op.f("ix_prompt_challenges_publish_date"),
        "prompt_challenges",
        ["publish_date"],
        unique=True,
    )
    op.create_index(
        op.f("ix_prompt_challenges_status"), "prompt_challenges", ["status"], unique=False
    )
    op.drop_column("prompt_challenges", "difficulty")
    op.drop_column("prompt_challenges", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt_challenges", sa.Column("category", sa.VARCHAR(length=50), nullable=False))
    op.add_column(
        "prompt_challenges", sa.Column("difficulty", sa.VARCHAR(length=20), nullable=False)
    )
    op.drop_index(op.f("ix_prompt_challenges_status"), table_name="prompt_challenges")
    op.drop_index(op.f("ix_prompt_challenges_publish_date"), table_name="prompt_challenges")
    op.create_index(
        op.f("ix_prompt_challenges_difficulty"), "prompt_challenges", ["difficulty"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_challenges_category"), "prompt_challenges", ["category"], unique=False
    )
    op.drop_column("prompt_challenges", "publish_date")
    op.drop_column("prompt_challenges", "status")
    # ### end Alembic commands ###
